server:
  port: 8091

#spring:
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: sa
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    database: h2
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    open-in-view: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/studyroom?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: studyroom
    password: test
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

security:
  oauth2:
    jwt:
      signkey: halfdev!@$&
  # jwt token 사용안할 때 주석해제
#    client:
#      client-id: testClientId
#      client-secret: testSecret
#    resource:
#      token-info-uri: http://localhost:8090/oauth/check_token